/**
 * Gasper Dominus API
 * API specs for Gasper Dominus, the ecosystem's master. Handles authentication, creation/management of applications and databases and also provides a superuser API. The superuser API is only available for those user accounts which has `is_admin` set to `true` in the mongoDB database used by Gasper. Apart from that, a default superuser is created every time a Gasper instance is launched whose  credentials are defined in the `admin` section of `config.toml`, the main configuration file. A sample configuration file is available in the [Gasper GitHub Repository](https://github.com/sdslabs/gasper) under the name of `config.sample.toml`.<br><br> **Note:-** Normally the applications and databases can only be managed by their owners but the superuser can bypass that check.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@sdslabs.co.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Context from './Context';
import InlineResponse2001Resources from './InlineResponse2001Resources';

/**
 * The Application model module.
 * @module model/Application
 * @version 1.0
 */
class Application {
    /**
     * Constructs a new <code>Application</code>.
     * @alias module:model/Application
     * @param name {String} Name of the application
     * @param password {String} Password required for SSH access to the application's docker container
     * @param gitUrl {String} Git Repository URL of the application
     * @param context {module:model/Context} 
     */
    constructor(name, password, gitUrl, context) { 
        
        Application.initialize(this, name, password, gitUrl, context);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, password, gitUrl, context) { 
        obj['name'] = name;
        obj['password'] = password;
        obj['git_url'] = gitUrl;
        obj['context'] = context;
    }

    /**
     * Constructs a <code>Application</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Application} obj Optional instance to populate.
     * @return {module:model/Application} The populated <code>Application</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Application();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('git_url')) {
                obj['git_url'] = ApiClient.convertToType(data['git_url'], 'String');
            }
            if (data.hasOwnProperty('git_access_token')) {
                obj['git_access_token'] = ApiClient.convertToType(data['git_access_token'], 'String');
            }
            if (data.hasOwnProperty('context')) {
                obj['context'] = Context.constructFromObject(data['context']);
            }
            if (data.hasOwnProperty('env')) {
                obj['env'] = ApiClient.convertToType(data['env'], {'String': 'String'});
            }
            if (data.hasOwnProperty('resources')) {
                obj['resources'] = InlineResponse2001Resources.constructFromObject(data['resources']);
            }
        }
        return obj;
    }

/**
     * Returns Name of the application
     * @return {String}
     */
    getName() {
        return this.name;
    }

    /**
     * Sets Name of the application
     * @param {String} name Name of the application
     */
    setName(name) {
        this['name'] = name;
    }
/**
     * Returns Password required for SSH access to the application's docker container
     * @return {String}
     */
    getPassword() {
        return this.password;
    }

    /**
     * Sets Password required for SSH access to the application's docker container
     * @param {String} password Password required for SSH access to the application's docker container
     */
    setPassword(password) {
        this['password'] = password;
    }
/**
     * Returns Git Repository URL of the application
     * @return {String}
     */
    getGitUrl() {
        return this.git_url;
    }

    /**
     * Sets Git Repository URL of the application
     * @param {String} gitUrl Git Repository URL of the application
     */
    setGitUrl(gitUrl) {
        this['git_url'] = gitUrl;
    }
/**
     * Returns Access token for cloning the application's git repository
     * @return {String}
     */
    getGitAccessToken() {
        return this.git_access_token;
    }

    /**
     * Sets Access token for cloning the application's git repository
     * @param {String} gitAccessToken Access token for cloning the application's git repository
     */
    setGitAccessToken(gitAccessToken) {
        this['git_access_token'] = gitAccessToken;
    }
/**
     * @return {module:model/Context}
     */
    getContext() {
        return this.context;
    }

    /**
     * @param {module:model/Context} context
     */
    setContext(context) {
        this['context'] = context;
    }
/**
     * Returns Environment variables required by the application
     * @return {Object.<String, String>}
     */
    getEnv() {
        return this.env;
    }

    /**
     * Sets Environment variables required by the application
     * @param {Object.<String, String>} env Environment variables required by the application
     */
    setEnv(env) {
        this['env'] = env;
    }
/**
     * @return {module:model/InlineResponse2001Resources}
     */
    getResources() {
        return this.resources;
    }

    /**
     * @param {module:model/InlineResponse2001Resources} resources
     */
    setResources(resources) {
        this['resources'] = resources;
    }

}

/**
 * Name of the application
 * @member {String} name
 */
Application.prototype['name'] = undefined;

/**
 * Password required for SSH access to the application's docker container
 * @member {String} password
 */
Application.prototype['password'] = undefined;

/**
 * Git Repository URL of the application
 * @member {String} git_url
 */
Application.prototype['git_url'] = undefined;

/**
 * Access token for cloning the application's git repository
 * @member {String} git_access_token
 */
Application.prototype['git_access_token'] = undefined;

/**
 * @member {module:model/Context} context
 */
Application.prototype['context'] = undefined;

/**
 * Environment variables required by the application
 * @member {Object.<String, String>} env
 */
Application.prototype['env'] = undefined;

/**
 * @member {module:model/InlineResponse2001Resources} resources
 */
Application.prototype['resources'] = undefined;






export default Application;

