/**
 * Gasper Kaze API
 * Handles authentication, creation/management of applications, databases, users and also provides a superuser API. <br><br> Only a superuser can avail the superuser API. A superuser can **grant/revoke** superuser privileges to other users. A default  superuser is created every time a Gasper instance is launched whose credentials are defined in the `admin` section of `config.toml`, the main configuration file. A sample configuration file is available [here](https://github.com/sdslabs/gasper/blob/develop/config.sample.toml#L37).<br><br> **Note:-** Normally the applications and databases can only be managed by their owners but the superuser can bypass that check.<br><br> **PS:-** If you want to programmatically generate a client for this API, you can find the corresponding OpenAPI specifications [here](https://github.com/sdslabs/gasper/tree/develop/docs/content/api/specs). We recommend using [OpenAPI-Generator](https://openapi-generator.tech/) for generating clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@sdslabs.co.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreatedUser model module.
 * @module model/CreatedUser
 * @version 1.0
 */
class CreatedUser {
    /**
     * Constructs a new <code>CreatedUser</code>.
     * @alias module:model/CreatedUser
     */
    constructor() { 
        
        CreatedUser.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreatedUser</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatedUser} obj Optional instance to populate.
     * @return {module:model/CreatedUser} The populated <code>CreatedUser</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatedUser();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('admin')) {
                obj['admin'] = ApiClient.convertToType(data['admin'], 'Boolean');
            }
            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {String}
     */
    getUsername() {
        return this.username;
    }

    /**
     * @param {String} username
     */
    setUsername(username) {
        this['username'] = username;
    }
/**
     * @return {String}
     */
    getEmail() {
        return this.email;
    }

    /**
     * @param {String} email
     */
    setEmail(email) {
        this['email'] = email;
    }
/**
     * Returns Field denoting superuser privileges
     * @return {Boolean}
     */
    getAdmin() {
        return this.admin;
    }

    /**
     * Sets Field denoting superuser privileges
     * @param {Boolean} admin Field denoting superuser privileges
     */
    setAdmin(admin) {
        this['admin'] = admin;
    }
/**
     * Returns User's identifier assigned by MongoDB
     * @return {String}
     */
    getId() {
        return this._id;
    }

    /**
     * Sets User's identifier assigned by MongoDB
     * @param {String} id User's identifier assigned by MongoDB
     */
    setId(id) {
        this['_id'] = id;
    }

}

/**
 * @member {String} username
 */
CreatedUser.prototype['username'] = undefined;

/**
 * @member {String} email
 */
CreatedUser.prototype['email'] = undefined;

/**
 * Field denoting superuser privileges
 * @member {Boolean} admin
 */
CreatedUser.prototype['admin'] = undefined;

/**
 * User's identifier assigned by MongoDB
 * @member {String} _id
 */
CreatedUser.prototype['_id'] = undefined;






export default CreatedUser;

