/**
 * Gasper Kaze API
 * Handles authentication, creation/management of applications, databases, users and also provides a superuser API. <br><br> Only a superuser can avail the superuser API. A superuser can **grant/revoke** superuser privileges to other users. A default  superuser is created every time a Gasper instance is launched whose credentials are defined in the `admin` section of `config.toml`, the main configuration file. A sample configuration file is available [here](https://github.com/sdslabs/gasper/blob/develop/config.sample.toml#L37).<br><br> **Note:-** Normally the applications and databases can only be managed by their owners but the superuser can bypass that check.<br><br> **PS:-** If you want to programmatically generate a client for this API, you can find the corresponding OpenAPI specifications [here](https://github.com/sdslabs/gasper/tree/develop/docs/content/api/specs). We recommend using [OpenAPI-Generator](https://openapi-generator.tech/) for generating clients.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: contact@sdslabs.co.in
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.GasperKazeApi);
  }
}(this, function(expect, GasperKazeApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new GasperKazeApi.CreatedApplication();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreatedApplication', function() {
    it('should create an instance of CreatedApplication', function() {
      // uncomment below and update the code to test CreatedApplication
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be.a(GasperKazeApi.CreatedApplication);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property git (base name: "git")', function() {
      // uncomment below and update the code to test the property git
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property context (base name: "context")', function() {
      // uncomment below and update the code to test the property context
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property env (base name: "env")', function() {
      // uncomment below and update the code to test the property env
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property resources (base name: "resources")', function() {
      // uncomment below and update the code to test the property resources
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property containerId (base name: "container_id")', function() {
      // uncomment below and update the code to test the property containerId
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property containerPort (base name: "container_port")', function() {
      // uncomment below and update the code to test the property containerPort
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property dockerImage (base name: "docker_image")', function() {
      // uncomment below and update the code to test the property dockerImage
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property appUrl (base name: "app_url")', function() {
      // uncomment below and update the code to test the property appUrl
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property hostIp (base name: "host_ip")', function() {
      // uncomment below and update the code to test the property hostIp
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property nameServers (base name: "name_servers")', function() {
      // uncomment below and update the code to test the property nameServers
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property instanceType (base name: "instance_type")', function() {
      // uncomment below and update the code to test the property instanceType
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property language (base name: "language")', function() {
      // uncomment below and update the code to test the property language
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property owner (base name: "owner")', function() {
      // uncomment below and update the code to test the property owner
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property sshCmd (base name: "ssh_cmd")', function() {
      // uncomment below and update the code to test the property sshCmd
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new GasperKazeApi.CreatedApplication();
      //expect(instance).to.be();
    });

  });

}));
